"""initial schema

Revision ID: 309b33ebec31
Revises:
Create Date: 2026-05-06 01:45:20.103401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '309b33ebec31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('result_hash', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_agent_id'), 'actions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_actions_decision'), 'actions', ['decision'], unique=False)
    op.create_index(op.f('ix_actions_task_id'), 'actions', ['task_id'], unique=False)
    op.create_index(op.f('ix_actions_tool'), 'actions', ['tool'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('receipt_type', sa.String(length=64), nullable=False),
    sa.Column('merkle_leaf_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('signature_ed25519_b64', sa.String(length=8192), nullable=True),
    sa.Column('signature_mldsa_b64', sa.String(length=8192), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_created_at'), 'receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_receipts_merkle_leaf_index'), 'receipts', ['merkle_leaf_index'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_type'), 'receipts', ['receipt_type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_created_at'), 'entities', ['created_at'], unique=False)
    op.create_index(op.f('ix_entities_source_id'), 'entities', ['source_id'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_index('ix_entities_type_created', 'entities', ['type', 'created_at'], unique=False)
    op.create_index(op.f('ix_entities_updated_at'), 'entities', ['updated_at'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_created_at'), 'edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_edges_relationship'), 'edges', ['relationship'], unique=False)
    op.create_index(op.f('ix_edges_source_id'), 'edges', ['source_id'], unique=False)
    op.create_index('ix_edges_src_rel', 'edges', ['source_id', 'relationship'], unique=False)
    op.create_index(op.f('ix_edges_target_id'), 'edges', ['target_id'], unique=False)
    op.create_index('ix_edges_tgt_rel', 'edges', ['target_id', 'relationship'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('skill_hash', sa.String(length=128), nullable=False),
    sa.Column('process_entity_id', sa.String(length=32), nullable=False),
    sa.Column('emitted_at', sa.DateTime(), nullable=False),
    sa.Column('signed_metadata', sqlite.JSON(), nullable=False),
    sa.Column('markdown', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['process_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_emitted_at'), 'skills', ['emitted_at'], unique=False)
    op.create_index(op.f('ix_skills_process_entity_id'), 'skills', ['process_entity_id'], unique=False)
    op.create_index(op.f('ix_skills_scope'), 'skills', ['scope'], unique=False)
    op.create_index(op.f('ix_skills_skill_hash'), 'skills', ['skill_hash'], unique=False)
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skills_version'), 'skills', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_version'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill_hash'), table_name='skills')
    op.drop_index(op.f('ix_skills_scope'), table_name='skills')
    op.drop_index(op.f('ix_skills_process_entity_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_emitted_at'), table_name='skills')
    op.drop_table('skills')
    op.drop_index('ix_edges_tgt_rel', table_name='edges')
    op.drop_index(op.f('ix_edges_target_id'), table_name='edges')
    op.drop_index('ix_edges_src_rel', table_name='edges')
    op.drop_index(op.f('ix_edges_source_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_relationship'), table_name='edges')
    op.drop_index(op.f('ix_edges_created_at'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_entities_updated_at'), table_name='entities')
    op.drop_index('ix_entities_type_created', table_name='entities')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_source_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_created_at'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_receipts_receipt_type'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_merkle_leaf_index'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_created_at'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_actions_tool'), table_name='actions')
    op.drop_index(op.f('ix_actions_task_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_decision'), table_name='actions')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    op.drop_index(op.f('ix_actions_agent_id'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
