export const RELATIONSHIP_COLORS = Object.freeze({
  PERSON_PARTICIPATES_IN_THREAD: "#8BE9FD",
  TICKET_ASSIGNED_TO_PERSON: "#FF79C6",
  TICKET_BELONGS_TO_PROCESS: "#50FA7B",
  DECISION_REFERENCES_THREAD: "#BD93F9",
  DECISION_REFERENCES_DOCUMENT: "#BD93F9",
  DOCUMENT_REFERENCED_BY_PROCESS: "#F1FA8C",
  PROCESS_DESCRIBED_BY_DOCUMENT: "#50FA7B",
  CODE_IMPLEMENTS_PROCESS: "#7CFC9F",
  CODE_RESOLVES_TICKET: "#7CFC9F",
} as const);

export const FALLBACK_RELATIONSHIP_COLOR = "#FFFFFF";

export function colorForRelationship(rel: string): string {
  return RELATIONSHIP_COLORS[rel as keyof typeof RELATIONSHIP_COLORS] ?? FALLBACK_RELATIONSHIP_COLOR;
}
